# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='home/photos/')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(max_length=200)),
                ('itemType', models.CharField(help_text='Office Use/Academic Use', max_length=100)),
                ('courseName', models.CharField(blank=True, help_text='Leave blank if Office Use', max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('itemName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Item')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=21)),
                ('password', models.CharField(max_length=26)),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(blank=True, help_text='Leave blank if personnel/faculty', max_length=100)),
                ('office', models.CharField(blank=True, help_text='Leave blank if student', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
