# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170726_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.CharField(max_length=1000),
        ),
    ]
