# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170727_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
