# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170727_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
