# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170727_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.CharField(choices=[('Office Use', 'OFFICE USE'), ('Academic Use', 'ACADEMIC USE')], default='Academic Use', max_length=100),
        ),
    ]
